define({
  plaqueMessageSmall: {},
  buttonText: {},

  winningNumbersTitle: {
    fontFamily: 'oswald',
    fontWeight: 'bold',
    fontSize: 32,
    fill: 'fontColourLuckyNumberTitle',
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },
  playerNumbersTitle: {
    fontFamily: 'oswald',
    fontWeight: 'bold',
    fontSize: 32,
    fill: 'fontColourYourNumberTitle',
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },

  prizeValueNoWin: {
    fontFamily: 'oswald',
    fontSize: 30,
    fontWeight: 'bold',
    fill: 'fontColourCashValueNoWin',
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },
  prizeValueWin: {
    fontFamily: 'oswald',
    fontSize: 30,
    fontWeight: 'bold',
    fill: 'fontColourCashValueWin',
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },

  winUpToText: {
    fontFamily: 'oswald',
    fontSize: 28,
    fontWeight: 'bold',
    fill: 'fontColourWinUpToTitle',
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },

  winUpToValue: {
    fontFamily: 'oswald',
    fontSize: 54,
    fontWeight: 'bold',
    fill: 'fontColourWinUpToTitle',
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },

  bonusWin6: {
    fontFamily: 'oswald',
    fontSize: 92,
    fontWeight: 'bold',
    align: 'center',
    fill: ['#c38d46', '#e1c070', '#f9e896'],
    fillGradientStops: [0.1, 0.7, 0.8],
    fillGradientType: 0,

  },
  bonusNoWin6: {
    fontFamily: 'oswald',
    fontSize: 92,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#c2c9dd", "white", "#c2c9dd"],
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,

  },
  bonusWin5: {
    fontFamily: 'oswald',
    fontSize: 82,
    fontWeight: 'bold',
    align: 'center',
    fill: ['#c38d46', '#e1c070', '#f9e896'],
    fillGradientStops: [0.1, 0.7, 0.8],
    fillGradientType: 0,
  },
  bonusNoWin5: {
    fontFamily: 'oswald',
    fontSize: 82,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#c2c9dd", "white", "#c2c9dd"],
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },
  bonusWin4: {
    fontFamily: 'oswald',
    fontSize: 72,
    fontWeight: 'bold',
    align: 'center',
    fill: ['#c38d46', '#e1c070', '#f9e896'],
    fillGradientStops: [0.1, 0.7, 0.8],
    fillGradientType: 0,
  },
  bonusNoWin4: {
    fontFamily: 'oswald',
    fontSize: 72,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#c2c9dd", "white", "#c2c9dd"],
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },
  bonusWin3: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: ['#c38d46', '#e1c070', '#f9e896'],
    fillGradientStops: [0.1, 0.7, 0.8],
    fillGradientType: 0,
  },
  bonusNoWin3: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#c2c9dd", "white", "#c2c9dd"],
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },
  bonusWin: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: ['#c38d46', '#e1c070', '#f9e896'],
    fillGradientStops: [0.1, 0.7, 0.8],
    fillGradientType: 0,
  },
  bonusNoWin: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#c2c9dd", "white", "#c2c9dd"],
    dropShadow: true,
    dropShadowAngle: 0,
    dropShadowBlur: 5,
    dropShadowDistance: 0,
  },
  losePlaqueBody: {
    fontFamily: 'oswald',
    fontSize: 70,
    fontWeight: 'bold',
    align: 'center',
    fill: 'fontColourEndOfGameMessageNoWinBodyText',
    padding: 10,
  },
  winPlaqueBody: {
    fontFamily: 'oswald',
    fontSize: 60,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#FFF6BD", "#C9A053", "#FFF6BD"],
    fillGradientStops: [
      0.3,
      0.5,
      0.7
    ],
    padding: 10,
    dropShadow: true,
    dropShadowAngle: 0.1,
    dropShadowBlur: 6,
    dropShadowDistance: 0,
  },
  winPlaqueValue: {
    fontFamily: 'oswald',
    fontSize: 100,
    fontWeight: 'bold',
    //fill: 'fontColourEndOfGameMessageWinValue',
    fill: ["white", "#c2c9dd"],
    stroke: "white",
    strokeThickness: 4,
    padding: 10,
    dropShadow: true,
    dropShadowAngle: 0.1,
    dropShadowBlur: 6,
    dropShadowDistance: 0,
  },
  winAllBody: {
    fontFamily: 'oswald',
    fontSize: 60,
    fontWeight: 'bold',
    align: 'center',
    fill: ["#FFF6BD", "#C9A053", "#FFF6BD"],
    fillGradientStops: [
      0.3,
      0.5,
      0.7
    ],
    padding: 10,
    dropShadow: true,
    dropShadowAngle: 0.1,
    dropShadowBlur: 6,
    dropShadowDistance: 0,
  },
  winAllValue: {
    fontFamily: 'oswald',
    fontSize: 120,
    fontWeight: 'bold',
    fill: ["#c2c9dd", "white", "#c2c9dd"],
    //fill: 'fontColourEndOfGameMessageWinValue',
    padding: 10,
  },
  bonusLabel: {
    fontFamily: 'oswald',
    fontSize: 32,
    fontWeight: 'bold',
    fill: 'fontColourBonusCover',
  },
  bonusFind3ToEnd: {
    fontFamily: 'oswald',
    fontSize: 30,
    fontWeight: 'bold',
    fill: 'bonusFind3ToEndTextColour',
  },
  bonusFind3ToWin: {
    fontFamily: 'oswald',
    fontSize: 30,
    fontWeight: 'bold',
    fill: 'bonusFind3ToWinTextColour',
  },

  buyButtonEnabled: {
    fontFamily: 'oswald',
    fontSize: 38,
    fill: 'buyButtonEnabledFontColour',
    padding: 10,
  },
  buyButtonDisabled: {
    fontFamily: 'oswald',
    fontSize: 38,
    fill: 'buyButtonDisabledFontColour',
    padding: 10,
  },
  buyButtonOver: {
    fontFamily: 'oswald',
    fontSize: 38,
    fill: 'buyButtonOverFontColour',
    padding: 10,
  },
  buyButtonPressed: {
    fontFamily: 'oswald',
    fontSize: 41,
    fill: 'buyButtonPressedFontColour',
    padding: 10,
  },
});